%  ** Structural dynamics parameters for beam element model (default) **

% Disclaimer:
%   SPDX-License-Identifier: GPL-3.0-only
% 
%   Copyright (C) 2024-2025 Yannic Beyer
%   Copyright (C) 2024-2025 TU Braunschweig, Institute of Flight Guidance
% *************************************************************************

% Node positions (global coordinates), m
param.xyz = [ ...
    -2, 0, 0; ...
    -1, 0, 0; ...
    0, 0, 0; ...
    1, 0, 0; ...
    2, 0, 0; ...
    0, 0, -1; ...
    0, 0, 1 ...
    ]';

% The beam element properties are specified in the local coordinates. The
% local coordinates for each beam element are as follows: x_local in the
% direction of the beam, y_local perpendicular to x_local and z_global,
% z_local perpendicular to x_local and y_local. If x_local and z_global are
% parallel, y_local is in the direction of y_global.
% Node mass, kg
m = 0.027;
% Node inertia w.r.t. node center of gravity, kg*m^2
Ixx = 1/12*0.017*0.04^2;
Iyy = 1/12*0.012*0.25^2;
Izz = Iyy;
% x, y, z: Node center of gravity w.r.t. node position, m
% m, x, y, z, Ixx, Iyy, Izz, Ixy, Ixz, Iyz
param.mass = [ ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    m, 0, 0, 0, Ixx, Iyy, Izz, 0, 0, 0; ...
    ];

% Young's modulus, N/m^2
E = 70e9;
% Shear modulus, N/m^2
G = E/2/1.2;
R = 0.008/2;
r = 0.006/2;
% Cross section area, m^2
A = pi*(R^2-r^2);
% Second moment of inertias (bending), m^4
Iy = pi/4*(R^4-r^4);
Iz = Iy;
% Second moment of inertia (torsion), m^4
J = pi/2*(R^4-r^4);
% Connect nodes with each other and define stiffness between these nodes
% Node 1 idx, node 2 idx, A, Iy, Iz, E, J, G
param.stiff = [ ...
    1, 2, A, Iy, Iz, E, J, G; ...
    2, 3, A, Iy, Iz, E, J, G; ...
    3, 4, A, Iy, Iz, E, J, G; ...
    4, 5, A, Iy, Iz, E, J, G; ...
    3, 6, A, Iy, Iz, E, J, G; ...
    3, 7, A, Iy, Iz, E, J, G; ...
    ];

