% ** Model requirements for tunability post-processing of code export (default) **
%
%   The model must fulfill these requirements so that the toolchain for
%   tunability post-processing of exported code can be used.
% 
% See also:
%   CHECKMODELREQS

% Disclamer:
%   SPDX-License-Identifier: GPL-3.0-only
% 
%   Copyright (C) 2024 Jonas Withelm
%   Copyright (C) 2024 TU Braunschweig, Institute of Flight Guidance
% *************************************************************************

param.param = {'IsERTTarget'; ...
               'SystemTargetFile'; ...
               'TargetLang'; ...
               'TunableVars'; ...
               'TunableVarsStorageClass'; ...
               'TunableVarsTypeQualifier'; ...
               'CustomHeaderCode'; ...
               'CustomSourceCode'};

param.value = {'on'; ...
               'ert.tlc'; ...
               'C++'; ...
               @(a) ~isempty(a); ...
               @(a) all(strcmp(strsplit(a, ','), 'Auto')); ...  % should be comma separated 'Auto'
               @(a) all(strcmp(strsplit(a, ','), '')); ...      % should be comma separated empty.char
               @(a) ~isempty(a) && startsWith(a, '//'); ...     % should be a C++ comment
               @(a) ~isempty(a) && startsWith(a, '//')};        % should be a C++ comment

param.err_desc = {'Wrong target'; ...
                  'Wrong target file'; ...
                  'Wrong target language'; ...
                  'No tunable variables'; ...
                  ''; ...
                  ''; ...
                  'No custom source file import identifier'; ...
                  'No custom header file import identifier'};
